Fix circle cI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,30 +8,64 @@ jobs:
     environment:
       CODECOV_TOKEN: "895aebcc-753e-49f2-b964-b70d38d471c4"
     steps:
+      - restore_cache:
+            keys:
+              - source-cache-hfo
+
       - checkout
+
+      - run:
+          name: Complete checkout
+          command: |
+            if ! git remote -v | grep upstream; then
+              git remote add upstream git://github.com/mne-tools/mne-hfo.git
+            fi
+            git fetch upstream
+
+      - save_cache:
+          key: source-cache-hfo
+          paths:
+            - ".git"
 
       # make sure pandoc is on the system
       - run: sudo apt update && sudo apt install -y pandoc
 
-      # restore cache from last build. Unless __init__.py has changed since then
+      # Load pip cache
       - restore_cache:
           keys:
-            - data-cache-0-{{ checksum "./mne_hfo/__init__.py" }}
-
-      # Also restore pip cache to speed up installations
-      - restore_cache: # ensure this step occurs *before* installing dependencies
+            - pip-cache
+      - restore_cache:
           keys:
-            # when lock file changes, use increasingly general patterns to restore cache
-            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
-            - pip-packages-v1-{{ .Branch }}-
-            - pip-packages-v1-
-
+            - user-install-bin-cache
+              
       - run:
-          name: Setup Python environment via Pipenv
+          name: Setup Python environment
           command: |
-            sudo pip install --upgrade pip
-            sudo pip install pipenv
-            pipenv install --skip-lock --dev
+            python -m pip install --upgrade --progress-bar off --only-binary matplotlib -r requirements_testing.txt
+            python -m pip install --upgrade --progress-bar off https://github.com/mne-tools/mne-python/zipball/main
+            python -m pip install --progress-bar off https://github.com/sphinx-gallery/sphinx-gallery/zipball/master
+            python -m pip install -e .
+
+      - save_cache:
+          key: pip-cache
+          paths:
+            - ~/.cache/pip
+
+      - save_cache:
+          key: user-install-bin-cache
+          paths:
+            - ~/.local/lib/python3.8/site-packages
+            - ~/.local/bin
+
+      # Look at what we have and fail early if there is some library conflict
+      - run:
+          name: Check installation
+          command: |
+              which python
+              python -c "import mne; mne.sys_info()"
+              LIBGL_DEBUG=verbose python -c "import matplotlib.pyplot as plt; plt.figure()"
+              python -c "import mne; mne.set_config('MNE_LOGGING_LEVEL', 'info')"
+              python -c "import mne; level = mne.get_config('MNE_LOGGING_LEVEL'); assert level.lower() == 'info', repr(level)"
 
       - run:
           name: Run unit and integration tests
@@ -41,7 +75,7 @@ jobs:
       - run:
           name: Build the documentation
           command: |
-            pipenv run make build-doc
+            make build-doc
 
       - persist_to_workspace:
           root: docs/_build
@@ -51,25 +85,12 @@ jobs:
           path: docs/_build/html/
           destination: dev
 
-      - store_artifacts:
-          path: ./coverage.xml
-
-      - run:
-          name: Upload codecov report
-          command: |
-            bash <(curl -s https://codecov.io/bash)
-
 #      - run:
 #          name: Check links
 #          command: |
 #            pipenv run make -C doc clean
 #            pipenv run make -C docs linkcheck
 #            pipenv run make -C doc linkcheck-grep
-
-      - save_cache:
-          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
-          paths:
-            - "~/.local/share/virtualenvs/venv"
 
   docs-deploy:
     # will only be run on master branch
